In [1]:
import numpy as np


# 1d array 

In [2]:
arr1=np.array([44,55,66,77])

In [3]:
arr1

array([44, 55, 66, 77])

In [4]:
arr1[2]


66

In [5]:
arr1d[1:3]

NameError: name 'arr1d' is not defined

In [6]:
arr1[1:3]

array([55, 66])

# 2D array

In [7]:
arr2d=([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
arr2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 2D ARRAY SLICING

In [11]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2d([:2],[1:])

SyntaxError: invalid syntax (<ipython-input-12-e6b10a90c2a5>, line 1)

In [13]:
arr2d[:2],[1:]

SyntaxError: invalid syntax (<ipython-input-13-54263c0de9ca>, line 1)

In [14]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

# 3d array

In [16]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [17]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# 3d slicing

In [18]:
arr3d[0][2]

array([7, 8, 9])

In [19]:
arr3d.shape

(1, 3, 3)

In [20]:
arr3d.ndim

3

In [21]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [22]:
arr3d[1][1]

array([13, 14, 15])

In [23]:
arr3d[1][1][1]

14

In [24]:
arr3d[0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
arr3d[0,:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr3d[0,:2,1:]

array([[2, 3],
       [5, 6]])

In [29]:
arr2d=np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]])
arr2d

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

arr2d[0:3,1:4] 

In [30]:
arr2d[0:3,1:4]

array([[4, 6, 8],
       [2, 3, 4],
       [0, 6, 2]])

In [31]:
arr2d[2:4,1:4]

array([[0, 6, 2],
       [6, 1, 5]])

In [37]:
arr3d=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30],[31,32,33,34,35,36]])
arr3d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [40]:
arr=np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [41]:
arr[4:,0:]

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [42]:
arr[4:5,0:]

array([[25, 26, 27, 28, 29, 30]])

In [45]:
arr[1:5,]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [46]:
arr[1:5]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [47]:
arr[2:4,5:]

array([[18],
       [24]])

In [49]:
arr[2:4,-1:]

array([[18],
       [24]])

In [50]:
arr[:,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [51]:
arr[:,::-2]  

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [52]:
arr[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

# :: step

# BOOLEAN INDEXING


In [53]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [54]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [55]:
data=np.random.randn(7,4)
data

array([[-0.3960881 ,  0.05085985, -0.0028062 ,  0.36909989],
       [-1.77692156,  0.21847868,  0.63488089,  1.5576694 ],
       [-1.36307064,  0.18318997, -1.13456368, -1.30220633],
       [ 0.6215574 , -0.03009685, -0.5692941 , -0.36653291],
       [-0.35564973, -1.03069833,  1.19194268,  0.45887626],
       [-1.21855953,  0.05215335,  0.48988217, -1.19029665],
       [-0.26132489,  1.21628777,  2.61912338, -1.11431253]])

In [56]:
names == "saad"

array([False, False, False, False, False, False, False])

In [57]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [58]:
data>1

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False,  True,  True, False]])

# for values

In [59]:
data[data>1]

array([1.5576694 , 1.19194268, 1.21628777, 2.61912338])

In [60]:
data[names=="Bob"]

array([[-0.3960881 ,  0.05085985, -0.0028062 ,  0.36909989],
       [ 0.6215574 , -0.03009685, -0.5692941 , -0.36653291]])

In [61]:
#those values which are true bring the data of the true condition that's why two rows are shown

In [62]:
#is we want 1 and 5 rows then

In [63]:
data[True,False,False,False,False,True,False]

array([], shape=(0, 7, 4), dtype=float64)

In [64]:
bol=np.array([True,False,False,False,False,True,False],dtype="bool")
data[bol]

array([[-0.3960881 ,  0.05085985, -0.0028062 ,  0.36909989],
       [-1.21855953,  0.05215335,  0.48988217, -1.19029665]])

In [65]:
data[names !="Bob"]

array([[-1.77692156,  0.21847868,  0.63488089,  1.5576694 ],
       [-1.36307064,  0.18318997, -1.13456368, -1.30220633],
       [-0.35564973, -1.03069833,  1.19194268,  0.45887626],
       [-1.21855953,  0.05215335,  0.48988217, -1.19029665],
       [-0.26132489,  1.21628777,  2.61912338, -1.11431253]])

In [66]:
condition=names !="Bob"
data[condition]

array([[-1.77692156,  0.21847868,  0.63488089,  1.5576694 ],
       [-1.36307064,  0.18318997, -1.13456368, -1.30220633],
       [-0.35564973, -1.03069833,  1.19194268,  0.45887626],
       [-1.21855953,  0.05215335,  0.48988217, -1.19029665],
       [-0.26132489,  1.21628777,  2.61912338, -1.11431253]])

 data[~condition]  # ~ REVERSE THE CONDITION

In [68]:
data[~condition]

array([[-0.3960881 ,  0.05085985, -0.0028062 ,  0.36909989],
       [ 0.6215574 , -0.03009685, -0.5692941 , -0.36653291]])

In [69]:
data[~condition,3]

array([ 0.36909989, -0.36653291])

In [70]:
data[condition,1:3]

array([[ 0.21847868,  0.63488089],
       [ 0.18318997, -1.13456368],
       [-1.03069833,  1.19194268],
       [ 0.05215335,  0.48988217],
       [ 1.21628777,  2.61912338]])

In [71]:
data=np.arange(28).reshape(7,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [72]:
print(condition)

[False  True  True False  True  True  True]


In [74]:
data[condition]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [76]:
data[condition,1:3]

array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [77]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

# and(&)

In [79]:
cond=(names == "Bob") & (names == "Joe")
cond

array([False, False, False, False, False, False, False])

# or(|)

In [80]:
cond=(names == "Bob") | (names == "Joe")
cond

array([ True,  True, False,  True, False,  True,  True])

# Fancy Indexing

In [81]:
arr=np.empty((8,4))
arr

array([[5.09279314e-313, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.50661734e-312, 0.00000000e+000, 2.55905223e-307,
        0.00000000e+000],
       [1.27320073e-313, 0.00000000e+000, 8.34674321e-309,
        0.00000000e+000],
       [1.50661734e-312, 0.00000000e+000, 2.55905224e-307,
        0.00000000e+000],
       [1.50661734e-312, 0.00000000e+000, 2.55905224e-307,
        0.00000000e+000],
       [1.27320073e-313, 0.00000000e+000, 8.34674354e-309,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [82]:
for i in range(8):
  arr[i] = i


In [5]:
arr

NameError: name 'arr' is not defined

In [3]:
arr[[1,2,3]]

NameError: name 'arr' is not defined

In [4]:
arr[[4,0,1,7]]

NameError: name 'arr' is not defined

In [87]:
arr[[4,0,1,7],[2,5,7,1]]

IndexError: index 5 is out of bounds for axis 1 with size 4

In [88]:
arr[[4,0,1,2],[2,3,0,1]]  #(4,2),(0,3),(1,0),(2,1)

array([4., 0., 1., 2.])

In [95]:
arr=np.arange(32).reshape(8,4)
print(arr)
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
# 1[0, 3, 1, 2],5[0, 3, 1, 2],7[0, 3, 1, 2],2[0, 3, 1, 2]
# (1,0),(1,3),(1,1)...........


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [96]:
arr.T  # FOR TRANSPOSE

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [97]:
arr.transpose()  # FOR TRANSPOSE

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [98]:
a=[22,23,24,25,22,26,25]
st=set(a)
st
#  set() REMOVE THE REPITATIVE DATA

{22, 23, 24, 25, 26}

In [99]:
#any() if any one is true then true
#all() if all s true then true

# Concatenating and Splitting Arrays


In [100]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1


array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [102]:
np.concatenate([arr1, arr2], axis=0) #when axis 0 then rows will increased


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [103]:
 np.concatenate([arr1, arr2], axis=1) #when axis 1 then columns will increased

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [104]:
np.stack([arr1,arr2])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [105]:
np.vstack([arr1,arr2]) # vstack rows will be incresed

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [106]:
np.hstack([arr1,arr2])  # hstack column will be incresed

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# split array

In [113]:
arr=np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [114]:
np.vsplit(arr,2) #in vsplit we split horizontally

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [10]:
import numpy as np
arr=np.arange(36).reshape(6,6)
np.hsplit(arr,3) #in hsplit we split vertically


[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]