# BROADCASTING(row and column must be 1 length)

In [1]:
import numpy as np

In [15]:
x=np.array([[1,2,3]])
print(x.shape)

y=np.array([[4],[5]])
print(y.shape)

(1, 3)
[[1 2 3]]
(2, 1)


In [13]:
x,y=np.broadcast_arrays(x,y)

In [10]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [11]:
y

array([[4, 4, 4],
       [5, 5, 5]])

(1, 3)
