In [2]:
import numpy as np

List vs Numpy Time-Taken

In [3]:
from time import process_time

Time taken by List

In [4]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for  i in python_list]

end_time=process_time()

print( end_time - start_time)

0.0015344340000000845


In [5]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array += 5

end_time=process_time()

print( end_time - start_time)

0.00027202100000001117


Numpy **Arrays**

In [6]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Creating 1 Dimensional Array

In [8]:
a=np.array([1,2,4,5])
print(a)

[1 2 4 5]


In [9]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype='float')
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [11]:
b.shape

(2, 4)

Initialize Placeholder in Numpy Array

In [12]:
x=np.zeros((4,5))
print(x)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Array of Particular Value

In [14]:
z=np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [15]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Create A Numpy Array with Random Values

In [16]:
b=np.random.random((3,4))
print(b)

[[0.21381061 0.04742996 0.9619353  0.10242288]
 [0.58899337 0.93591036 0.53599194 0.98489639]
 [0.07989482 0.61253059 0.85192146 0.15215778]]


random Integer value array within a specific Range

In [18]:
b=np.random.randint(10,100,(3,5))
print(b)

[[51 18 77 12 52]
 [21 50 55 13 91]
 [43 34 74 84 30]]


Array of Evenly spaced Values--->specifying the number of Values


In [19]:
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [23]:
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


Array of Evenly spaced Values--->specifying the Steps


In [24]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


Convert list toa an Numpy Array


In [26]:
list2=[1,2,3,4,5]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Analysing A Numpy Array


In [28]:
c=np.random.randint(10,90,(5,5))
print(c)

[[35 17 18 33 17]
 [35 37 51 34 54]
 [77 86 42 76 32]
 [31 78 40 84 15]
 [37 55 37 40 59]]


In [29]:
print(c.shape)

(5, 5)


In [30]:
print(c.ndim)

2


Number of Elements in An Array


In [31]:
print(c.size)

25


Checking the Datatypes of the values in the Array

In [32]:
print(c.dtype)


int64


Methematical Operations on np Array

In [33]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [34]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 0 0]
 [3 7 7]
 [4 0 2]]
[[17 14 11]
 [15 11 14]
 [13 12 18]]


In [35]:
print(a + b)

[[21 14 11]
 [18 18 21]
 [17 12 20]]


In [36]:
print(a - b)

[[-13 -14 -11]
 [-12  -4  -7]
 [ -9 -12 -16]]


In [37]:
print(a * b)

[[68  0  0]
 [45 77 98]
 [52  0 36]]


In [38]:
print(a/b)

[[0.23529412 0.         0.        ]
 [0.2        0.63636364 0.5       ]
 [0.30769231 0.         0.11111111]]


In [39]:
print(np.add(a,b))

[[21 14 11]
 [18 18 21]
 [17 12 20]]


In [40]:
print(np.subtract(a,b))

[[-13 -14 -11]
 [-12  -4  -7]
 [ -9 -12 -16]]


In [41]:
print(np.multiply(a,b))

[[68  0  0]
 [45 77 98]
 [52  0 36]]


In [42]:
print(np.divide(a,b))

[[0.23529412 0.         0.        ]
 [0.2        0.63636364 0.5       ]
 [0.30769231 0.         0.11111111]]


Array Manipulation

In [45]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 9 9]
 [6 0 8]]
(2, 3)


Transpose


In [46]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[8 6]
 [9 0]
 [9 8]]
(3, 2)


In [47]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 6 6]
 [7 1 5]]
(2, 3)


In [48]:
trans2=array.T
print(trans)
print(trans2.shape)

[[8 6]
 [9 0]
 [9 8]]
(3, 2)


Reshaping An Array


In [49]:
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 4 7]
 [3 3 2]]
(2, 3)


In [51]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[8 4]
 [7 3]
 [3 2]]
(3, 2)
